Fix a one-character typo. The effects of which were "Console"->"Ttys" menu would not launch (and gave no error). This was easily diagnosed by running `bsdconfig -d' as root and seeing the following error right after selecting the "Ttys" sub-menu:
DEBUG: f_getvar: var=[text] value=[
Error: Expected at least 6 tokens for --menu, have 4.
Use --help to list options.] r=0

Typo was introduced by SVN r251361.


git-svn-id: https://svn.freebsd.org/base/head@251552 ccf9f872-aa2e-dd11-9fc8-001c23d0bc1f